apiVersion: ansible.crossplane.io/v1alpha1
kind: PlaybookSet
metadata:
  name: example
spec:
  forProvider:
    # PlaybookSet default to using a remote source - like playbookSet-remote.yaml.
    # For simple cases you can use an inline source to specify the content of
    # playbook.yaml as opaque, inline yaml.
    source: Inline
    module: |
      ---
      - hosts: localhost
        tasks:
          - name: ansibleplaybook-simple
            debug:
              msg: Your are running 'ansibleplaybook-simple' example
  providerConfigRef:
    name: default